name: Build

on:
  pull_request:
    types: [ created ]
    branches: [ master ]
  release:
    types: [ created, edited ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2
      -
        name: Cache
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ matrix.os }}-build
      -
        name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DTMPL_LIB_BUILD_SHARED=ON
      -
        name: Build lib
        run: cmake --build build --config Release --target lib -j2
      -
        name: Build app
        run: cmake --build build --config Release --target app -j2
      -
        name: Pack
        run: cmake --build build --config Release --target package -j2
      -
        if: github.event_name == 'pull_request'
        name: Upload
        uses: actions/upload-artifact@main
        with:
          path: build/*.zip
          name: ${{ matrix.cfg.name }}-artefact
      -
        if: github.event_name == 'release'
        id: prepare
        name: Get name
        shell: bash
        run: echo ::set-output name=artefact::$(ls _build/ | grep .zip)
      -
        if: github.event_name == 'release'
        name: Deploy artefacts
        uses: actions/upload-release-asset@v1.0.1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/${{ steps.prepare.outputs.artefact }}
          asset_name: ${{ matrix.os }}-${{ steps.prepare.outputs.artefact }}
          asset_content_type: application/zip
