name: Build

on: push

jobs:
   build:
      name: ${{ matrix.name }}
      runs-on: ${{ matrix.cfg.os }}
      strategy:
         matrix:
           cfg:
            -
               name: MacOS
               os: macos-latest
               flags: -- -j2
            -
               name: Windows
               os: windows-latest
               flags: ''
            -
               name: Linux
               os: ubuntu-latest
               flags: -- -j2

      steps:
        - uses: actions/checkout@v2
        -
          name: Cache
          id: deps
          uses: actions/cache@v2
          with:
            path: $VCPKG_INSTALLATION_ROOT/install
            key: ${{ matrix.cfg.name }}-deps
        -
          name: Setup dependencies
          if: steps.deps.outputs.cache-hit != 'true'
          run: vcpkg install catch2
        -
          name: Configure
          env:
            CMAKE_PREFIX_PATH: deps
          run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DTMPL_LIB_BUILD_SHARED=ON -DTMPL_LIB_BUILD_TESTS=ON -DTMPL_LIB_BUILD_EXAMPLES=ON
        -
          name: Tests
          run: cmake --build build --config Release --target lib_test_first ${{ matrix.cfg.flags }}
        -
          name: Build lib
          run: cmake --build build --config Release --target lib ${{ matrix.cfg.flags }}
        -
          name: Build app
          run: cmake --build build --config Release --target app ${{ matrix.cfg.flags }}

