name: Documentation

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: prep
        run: |
          mkdir -p ${{ github.workspace }}/out
          ls -la ${{ github.workspace }}
      - uses: addnab/docker-run-action@v3
        with:
          image: standardese/standardese
          options: -v ${{ github.workspace }}/lib/include/tmpl:/headers:ro -v ${{ github.workspace }}/out:/home/standardese
          run: standardese /headers --compilation.standard=c++17
      - name: copy
        run: |
          ls -la ${{ github.workspace }}/out
          #cp ${{ github.workspace }}/out/doc_example.md ${{ github.workspace }}/wiki/example.md
      - name: Commit files
        working-directory: wiki
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes"
          git push

