name: Documentation

on:
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: cmake -S . -B build
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          path: wiki
      - name: prep
        run: mkdir -m=777 -p out
      - uses: addnab/docker-run-action@v3
        with:
          image: standardese/standardese
          options: 
            -v ${{ github.workspace }}/lib/include/tmpl:/headers:ro
            -v ${{ github.workspace }}/build/lib:/includes:ro
            -v ${{ github.workspace }}/out:/home/standardese
          run: standardese /headers -I /includes --compilation.standard=c++17
      - name: copy
        run: cp out/doc_example.md wiki/example.md
      - name: Commit files
        working-directory: wiki
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add changes"
          git push

