name: Test

on:
  push:
  pull_request:
    types: [ created, edited ]
    branches: [ master ]
  release:
    types: [ created, edited ]

jobs:
  test:
    name: ${{ matrix.cfg.name }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      fail-fast: false
      matrix:
        cfg:
          -
            name: macos
            os: macos-latest
            flags: ''
          -
            name: windows x64
            os: windows-latest
            flags: -DCMAKE_GENERATOR_PLATFORM=x64
          -
            name: windows x32
            os: windows-latest
            flags: -DCMAKE_GENERATOR_PLATFORM=Win32
          -
            name: windows arm
            os: windows-latest
            flags: -DCMAKE_GENERATOR_PLATFORM=ARM
          -
            name: windows arm64
            os: windows-latest
            flags: -DCMAKE_GENERATOR_PLATFORM=ARM64
          -
            name: ubuntu
            os: ubuntu-latest
            flags: ''

    steps:
      - uses: actions/checkout@v2
      -
        name: Cache
        uses: actions/cache@v2
        with:
          path: build
          key: ${{ matrix.cfg.os }}-test
      -
        name: Configure
        run: cmake ${{ matrix.cfg.flags }} -S . -B build -DCMAKE_BUILD_TYPE=Debug -DTMPL_LIB_BUILD_SHARED=OFF -DTMPL_BUILD_TESTS=ON
      -
        name: Build
        run: cmake --build build --config Debug -j2
      -
        name: Tests
        working-directory: build
        run: ctest -C Debug -j2
